/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-generated.d.ts --include-runtime=false` (hash: 989a36c8b7a6163425fe075c555163cb)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./build/cloudflare-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
