'use client';
import {useEffect,useState} from 'react';
import {emailClient,trainingFetch} from '../../lib/email-client';
import {registrationEnabled} from '../../lib/email-config';
type Mode='signin'|'signup'|'recover'|'update';
export default function AccountForm(){
 const [mode,setMode]=useState<Mode>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [account,setAccount]=useState<string|null>(null);
 useEffect(()=>{void emailClient().auth.getSession().then(({data})=>setAccount(data.session?.user.email??null));const {data:{subscription}}=emailClient().auth.onAuthStateChange((event,session)=>{setAccount(session?.user.email??null);if(event==='PASSWORD_RECOVERY')setMode('update');});return()=>subscription.unsubscribe();},[]);
 async function importPrevious(){setError('');setBusy(true);try{const r=await trainingFetch('/api/account/import',{method:'POST'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error??'Import failed.');setMessage('Previous workouts imported. Existing email-account entries were preserved.');}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{
  const auth=emailClient().auth,redirectTo=`${location.origin}/account`;
  if(mode==='signup'||mode==='recover'){if(!registrationEnabled)throw Error('Account email setup is being completed. Registration and password recovery will open once the final checks pass.');}
  if(mode==='signin'){const r=await auth.signInWithPassword({email:email.trim(),password});if(r.error)throw r.error;location.assign('/');}
  if(mode==='signup'){const r=await auth.signUp({email:email.trim(),password,options:{emailRedirectTo:redirectTo}});if(r.error)throw r.error;setPassword('');setMessage('Check your inbox to confirm your email, then sign in here.');}
  if(mode==='recover'){const r=await auth.resetPasswordForEmail(email.trim(),{redirectTo});if(r.error)throw r.error;setMessage('If that address has an account, a reset link will arrive shortly.');}
  if(mode==='update'){const r=await auth.updateUser({password});if(r.error)throw r.error;setPassword('');location.assign('/');}
 }catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <main className="account-page"><section className="tool-card account-card"><a href="/" className="brand">NextSet.</a><h1>{mode==='signin'?'Sign in':mode==='signup'?'Create account':mode==='recover'?'Reset your password.':'Choose a new password.'}</h1><p className="muted">One Siahverse account for NextSet, NurseDoku, and Tasks.</p>{account&&mode!=='update'&&<section><p>Signed in as {account}</p><button className="secondary" onClick={async()=>{const {error}=await emailClient().auth.signOut({scope:'local'});if(error){setError(error.message);return;}location.assign('/');}}>Sign out of Siahverse</button><p className="help">Moving from your original NextSet login? Verify both accounts using the same email.</p><a href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Verify previous NextSet account</a><button className="secondary" disabled={busy} onClick={()=>void importPrevious()}>Import previous workouts</button></section>}<form onSubmit={submit}>{mode!=='update'&&<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='recover'&&<label>Password<input type="password" autoComplete={mode==='signin'?'current-password':'new-password'} minLength={mode==='signin'?1:12} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="primary" disabled={busy||(!registrationEnabled&&(mode==='signup'||mode==='recover'))}>{busy?'Working…':mode==='signin'?'Sign in':mode==='signup'?'Create account':mode==='recover'?'Send reset link':'Save password'}</button></form>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{!registrationEnabled&&<p className="help">New accounts and password-reset emails are temporarily unavailable while account setup is being completed. Existing Siahverse email accounts can sign in.</p>}<div className="account-links">{(['signin','signup','recover'] as Mode[]).map(m=><button className="secondary" key={m} onClick={()=>{setMode(m);setError('');setMessage('');setPassword('');}}>{m==='signin'?'Sign in':m==='signup'?'Create account':'Forgot password?'}</button>)}</div><p className="help">Use the same email account as your other Siahverse apps. On shared devices, sign out when finished.</p></section></main>;
}
