'use client';
import {useState} from 'react';
import {CustomDefinition,CustomProgram,customDefinition} from '../lib/custom-program';
import {trainingFetch} from '../lib/email-client';
const newExercise=()=>({id:crypto.randomUUID(),name:'',sets:3,min:8,max:12,unit:'reps' as const,restSeconds:120});
const newDay=(n:number)=>({label:'Day '+n,exercises:[newExercise()]});
export default function ProgramBuilder({initial,onSaved,onCancel}:{initial?:CustomProgram;onSaved:(p:CustomProgram)=>void;onCancel:()=>void}){
 const [draft,setDraft]=useState<CustomDefinition>(()=>initial?structuredClone(initial):{name:'',description:'',equipment:'',progression:'',days:[newDay(1)]}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function changeDay(i:number,patch:Partial<CustomDefinition['days'][number]>){setDraft(d=>({...d,days:d.days.map((day,j)=>i===j?{...day,...patch}:day)}));}
 function changeExercise(di:number,ei:number,patch:Partial<CustomDefinition['days'][number]['exercises'][number]>){changeDay(di,{exercises:draft.days[di].exercises.map((e,i)=>i===ei?{...e,...patch}:e)});}
 function move<T>(list:T[],i:number,step:number){const copy=[...list];[copy[i],copy[i+step]]=[copy[i+step],copy[i]];return copy;}
 async function save(){setError('');const checked=customDefinition.safeParse(draft);if(!checked.success){setError('Check your program: '+checked.error.issues[0].message);return;}setBusy(true);try{const r=await trainingFetch('/api/custom-programs',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...checked.data,...(initial?.id?{id:initial.id}:{})})});const data=await r.json() as {error?:string;program:CustomProgram};if(!r.ok)throw Error(data.error??'Could not save.');onSaved(data.program);}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <section className="workout-card program-builder"><p className="eyebrow">YOUR OWN ROUTINE</p><h2>{initial?.id?'Edit program':'Create a program'}</h2><p className="help">Build a weekly schedule that repeats. Save it privately to your account, then review and commit when ready. You can edit it before logging; after that, duplicate it to preserve your history.</p><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><label>Program name<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Description<textarea maxLength={500} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Equipment<input maxLength={200} value={draft.equipment} onChange={e=>setDraft({...draft,equipment:e.target.value})}/></label><label>Progression notes<textarea maxLength={1000} placeholder="When will you add reps or weight?" value={draft.progression} onChange={e=>setDraft({...draft,progression:e.target.value})}/></label>
 {draft.days.map((day,di)=><section className="builder-day" key={di}><div className="builder-day-heading"><label>Workout {di+1} name<input required maxLength={50} value={day.label} onChange={e=>changeDay(di,{label:e.target.value})}/></label><div className="builder-actions"><button type="button" className="secondary" aria-label={`Move workout ${di+1} up`} disabled={!di} onClick={()=>setDraft({...draft,days:move(draft.days,di,-1)})}>↑</button><button type="button" className="secondary" aria-label={`Move workout ${di+1} down`} disabled={di===draft.days.length-1} onClick={()=>setDraft({...draft,days:move(draft.days,di,1)})}>↓</button><button type="button" className="secondary" disabled={draft.days.length===1} onClick={()=>setDraft({...draft,days:draft.days.filter((_,i)=>i!==di)})}>Remove workout {di+1}</button></div></div>
 {day.exercises.map((ex,ei)=><section className="builder-exercise" key={ex.id}><label>Exercise {ei+1}<input required list="builder-exercises" maxLength={100} value={ex.name} onChange={e=>changeExercise(di,ei,{name:e.target.value})}/></label><div className="builder-fields"><label>Sets<input aria-label={`Workout ${di+1} exercise ${ei+1} sets`} type="number" min={1} max={10} required value={ex.sets} onChange={e=>changeExercise(di,ei,{sets:Number(e.target.value)})}/></label><label>Min<input aria-label={`Workout ${di+1} exercise ${ei+1} minimum`} type="number" min={1} max={ex.unit==='seconds'?3600:100} required value={ex.min} onChange={e=>changeExercise(di,ei,{min:Number(e.target.value)})}/></label><label>Max<input aria-label={`Workout ${di+1} exercise ${ei+1} maximum`} type="number" min={ex.min} max={ex.unit==='seconds'?3600:100} required value={ex.max} onChange={e=>changeExercise(di,ei,{max:Number(e.target.value)})}/></label><label>Unit<select aria-label={`Workout ${di+1} exercise ${ei+1} unit`} value={ex.unit} onChange={e=>changeExercise(di,ei,{unit:e.target.value as 'reps'|'seconds'})}><option value="reps">Reps</option><option value="seconds">Seconds</option></select></label><label>Rest (sec)<input aria-label={`Workout ${di+1} exercise ${ei+1} rest seconds`} type="number" min={0} max={600} required value={ex.restSeconds} onChange={e=>changeExercise(di,ei,{restSeconds:Number(e.target.value)})}/></label></div><div className="builder-actions"><button type="button" className="secondary" aria-label={`Move workout ${di+1} exercise ${ei+1} up`} disabled={!ei} onClick={()=>changeDay(di,{exercises:move(day.exercises,ei,-1)})}>↑</button><button type="button" className="secondary" aria-label={`Move workout ${di+1} exercise ${ei+1} down`} disabled={ei===day.exercises.length-1} onClick={()=>changeDay(di,{exercises:move(day.exercises,ei,1)})}>↓</button><button type="button" className="secondary" disabled={day.exercises.length===1} onClick={()=>changeDay(di,{exercises:day.exercises.filter((_,i)=>i!==ei)})}>Remove exercise {ei+1}</button></div></section>)}<button type="button" className="secondary" disabled={day.exercises.length>=20} onClick={()=>changeDay(di,{exercises:[...day.exercises,newExercise()]})}>+ Add exercise</button></section>)}
 <button type="button" className="secondary" disabled={draft.days.length>=7} onClick={()=>setDraft({...draft,days:[...draft.days,newDay(draft.days.length+1)]})}>+ Add workout day</button><div className="session-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" type="submit">{busy?'Saving…':'Save program'}</button></div></fieldset>{error&&<p className="error" role="alert">{error}</p>}<datalist id="builder-exercises">{['Push-Up','Pull-Up','Barbell Squat','Bench Press','Overhead Press','Barbell Row','Romanian Deadlift','Dumbbell Lunge','Dumbbell Lateral Raise','Bicep Curl','Face Pull','Standing Calf Raise','Plank','Ab Wheel'].map(name=><option key={name} value={name}/>)}</datalist></form></section>;
}
