'use client';
import {EntryLog} from '../lib/reentry';
import {trainingSummary} from '../lib/analytics';
export function ProgramsPanel({committed,busy,signedIn,onCommit,onTrain}:{committed:boolean;busy:boolean;signedIn:boolean;onCommit:()=>void;onTrain:()=>void}){
 return <><p className="eyebrow">FIND YOUR ROUTINE</p><h1 className="page-title">Programs.</h1><p className="muted">Choose your training plan. Coach programs will join the library as they become available.</p><article className="program-card workout-card"><div className="card-top"><span className="pill">HOME GYM</span><span className="help">By Siah</span></div><h2>At-Home PPL</h2><p>Push, Pull, Legs. Start with two comeback weeks, then build into a six-day routine you can follow indefinitely.</p><div className="program-tags"><span>3 → 6 workouts / week</span><span>Barbell · dumbbells · pull-up bar</span><span>Ongoing</span></div><details><summary>Preview the program</summary><p>Weeks 1–2: Push, Pull, and Legs once each. Target 3–4 RIR.</p><p>Week 3 onward: PPLPPL, with your existing exercise and set targets.</p><p>A rack, plates, dip setup, and a cable or band for face pulls may also be needed.</p></details><p className="help">We recommend committing to one program at a time so training and recovery stay manageable.</p>{committed?<button className="primary" onClick={onTrain}>Go to Train →</button>:signedIn?<button className="primary" disabled={busy} onClick={onCommit}>{busy?'Saving…':'Commit to program'}</button>:<a className="primary" href="/account">Sign in to commit</a>}</article></>;
}
export function AnalyticsOverview({logs,unit}:{logs:EntryLog[];unit:'lb'|'kg'}){
 const summary=trainingSummary(logs),latest=summary.records.at(-1),total=summary.volumeKg*(unit==='lb'?2.2046226218:1);
 return <><h1 className="page-title">This week.</h1><p className="muted">Your completed workouts, Monday to Sunday, in this device’s time zone.</p><div className="stats-grid"><div className="stat"><span>WORKOUTS</span><strong>{summary.thisWeek.length}</strong></div><div className="stat"><span>WEIGHT LIFTED</span><strong>{Math.round(total).toLocaleString()}<span>{unit} × reps</span></strong></div><div className="stat"><span>NEW PRS</span><strong>{summary.weekPRs.length}</strong></div></div><p className="help">Weight lifted counts added external load × reps, including added load on bodyweight exercises. First logged performances establish a baseline; subsequent improvements count as PRs.</p><div className="tools-grid"><section className="workout-card"><p className="eyebrow">LATEST PR</p>{latest?<><h2>{latest.name}</h2><p>{latest.weight} {latest.unit} × {latest.reps} · {new Date(latest.date).toLocaleDateString()}</p></>:<><h2>Your next milestone.</h2><p className="help">Log a baseline, then improve your weight or reps to earn a PR.</p></>}</section><section className="workout-card"><p className="eyebrow">WEEKLY REPORT</p><h2>{summary.thisWeek.length} workouts completed</h2><p>{summary.lastWeekCount} last week · {summary.weekPRs.length} new PRs this week.</p><p className="help">{summary.thisWeek.length?'Keep logging RIR and form so your progress reflects controlled sets.':'Your first completed workout will start this week’s report.'}</p></section><section className="workout-card"><p className="eyebrow">MUSCLE TRACKER</p><h2>This week’s coverage.</h2>{Object.entries(summary.muscles).map(([name,count])=><div className="pr-row" key={name}><span>{name}</span><strong>{count} sets</strong></div>)}<p className="help">Completed sets grouped by primary exercise focus. Indirect muscle work is not counted.</p></section><section className="workout-card"><p className="eyebrow">NEXT IN ANALYTICS</p><h2>Strength score.</h2><p className="help">Coming in the next phase: a transparent score based on your logged strength progression. No score is estimated from missing records.</p></section></div></>;
}
export function NexusPanel(){return <><p className="eyebrow">YOUR PERSONAL TRAINER</p><h1 className="page-title">Nexus.</h1><section className="workout-card nexus-card"><span className="pill">IN DEVELOPMENT</span><h2>A trainer in your corner.</h2><p>Nexus will help explain exercises, find equipment substitutions, review your logged training, and suggest progression you control.</p><p className="help">Live AI coaching is not connected yet. This space will become your conversation with Nexus once the AI service is configured.</p><div className="nexus-prompts"><span>“What can I use instead of face pulls?”</span><span>“Review my training this week.”</span><span>“Am I ready to add weight?”</span></div></section></>;
}
