import type {CustomProgram} from './custom-program';
import type {EntryExercise,ProgramWeek} from './reentry';
export const programIds=['at-home-ppl','basic-beginner','dumbbell-stopgap','recommended-routine'] as const;
export type BuiltinProgramId=typeof programIds[number];
export type ProgramId=string;
export const catalog=[
 {id:'at-home-ppl' as ProgramId,name:'At-Home PPL',author:'Siah',kind:'Home gym',equipment:'Barbell · dumbbells · pull-up bar',frequency:'3 → 6 workouts / week',description:'Two comeback weeks, then a six-day PPL routine with ongoing tracking.',notes:'Weeks 1–2: Push, Pull, Legs once each, with 3–4 RIR. Later weeks retain the existing PPLPPL schedule. A rack, plates, dip setup, and cable or band for face pulls may be needed.',progression:'In Week 2, add weight only when every set reaches the top of its range with good form and at least 3 RIR. All weight changes are yours to make.',source:null},
 {id:'basic-beginner' as ProgramId,name:'Basic Beginner Routine',author:'r/Fitness community',kind:'Beginner · barbell',equipment:'Barbell · rack · bench · chin-up bar',frequency:'3 workouts / week',description:'Alternate two full-body workouts with a rest day between sessions. Review your next program after three months.',notes:'A: rows, bench press, squat. B: chin-ups, overhead press, deadlift. Each lift has two sets of five and a final 5+ set; stop that final set with 1–2 reps left. Rest 2–3 minutes. Include cardio on two other days.',progression:'Source progression: add 2.5 lb total to upper-body lifts or 5 lb to lower-body lifts next session; double that increment after more than 10 reps in the final set. Below 15 total reps, reduce that lift by 10%. Adjust manually.',source:'https://thefitness.wiki/routines/r-fitness-basic-beginner-routine/'},
 {id:'dumbbell-stopgap' as ProgramId,name:'Dumbbell Stopgap',author:'Cammorak · r/Fitness',kind:'Beginner · dumbbells',equipment:'Adjustable dumbbells · floor space',frequency:'3 workouts / week',description:'An introductory A/B routine for limited equipment. Move to a fuller program when your equipment or goals outgrow it.',notes:'Alternate A/B/A, then B/A/B with rest days between workouts. NextSet uses the source’s lunge option. Use total weight of both dumbbells when logging. Plank entries use seconds. Start light and keep controlled form.',progression:'For lifting exercises, do three sets of up to 10 reps. Once all three reach 10, choose the next dumbbell increment. If stalled for three sessions, reduce two increments. Rest one minute. The source prescribes three plank holds for as long as possible; stop when position breaks down.',source:'https://old.reddit.com/r/Fitness/comments/zc0uy/a_beginner_dumbbell_program_the_dumbbell_stopgap/'},
 {id:'recommended-routine' as ProgramId,name:'Recommended Routine',author:'r/bodyweightfitness community',kind:'Bodyweight · full body',equipment:'Pull-up bar · row setup · dip bars · resistance band',frequency:'3 workouts / week',description:'The Reddit bodyweight routine: three strength pairs and a core triplet. Choose a suitable exercise progression for each movement.',notes:'Train three times weekly with a rest day between sessions. Warm up for 5–10 minutes. Alternate one set of each exercise in a pair, resting 90 seconds between exercises, for three rounds. Cycle through the core triplet with 60 seconds between exercises. Take longer rests when needed for good form. Select your variation in the workout logger; the easiest listed variations are initial defaults, not a fitness assessment.',progression:'Start rep-based strength variations at 3 × 5. Add reps toward 3 × 8 with good form, then manually choose a harder variation and return to 5. Core repetitions use 8–12; plank holds use 10–30 seconds; parallel-bar support holds build to 60 seconds. Leave about one rep in reserve. Read the source for technique, warm-up and progression prerequisites.',source:'https://www.reddit.com/r/bodyweightfitness/wiki/kb/recommended_routine/'}
];
export function isProgramId(id:unknown):id is ProgramId{return programIds.includes(id as BuiltinProgramId);}
export function programInfo(id:ProgramId,custom:CustomProgram[]=[]){const c=custom.find(p=>p.id===id);return c?{id:c.id,name:c.name,author:'You',kind:'Your program',equipment:c.equipment||'Your equipment',frequency:c.days.length+' workouts / week',description:c.description||'Your own weekly routine.',notes:'Repeat this weekly schedule. '+c.days.map(d=>d.label).join(' → '),progression:c.progression||'Adjust weights and reps yourself. Prioritize controlled form and recovery.',source:null}:catalog.find(p=>p.id===id)!;}
const lift=(id:string,name:string,min:number,max:number,unit='reps',amrap=false):EntryExercise=>({id,name,sets:3,min,max,targets:Array.from({length:3},(_,i)=>({min,max,unit})),amrap});
export function communityWeek(week:number,id:Exclude<BuiltinProgramId,'at-home-ppl'>):ProgramWeek{
 const basic=id==='basic-beginner';
 const a=basic?[lift('bb-row','Barbell Row',5,5,'reps',true),lift('bb-bench','Bench Press',5,5,'reps',true),lift('bb-squat','Barbell Squat',5,5,'reps',true)]:[lift('db-lunge','Dumbbell Lunge',1,10),lift('db-floor','Dumbbell Floor Press',1,10),lift('db-sldl','Dumbbell Straight-Leg Deadlift',1,10),lift('db-plank','Plank',1,3600,'seconds')];
 const b=basic?[lift('bb-chin','Chin-Up',5,5,'reps',true),lift('bb-ohp','Overhead Press',5,5,'reps',true),lift('bb-dead','Deadlift',5,5,'reps',true)]:[lift('db-lunge','Dumbbell Lunge',1,10),lift('db-press','Seated Dumbbell Shoulder Press',1,10),lift('db-row','Standing Two-Dumbbell Row',1,10),lift('db-plank','Plank',1,3600,'seconds')];
 return {week,title:'Full body A/B',days:(week%2?['A','B','A']:['B','A','B']).map(label=>({day:`Full Body ${label}` as 'Full Body A'|'Full Body B',exercises:structuredClone(label==='A'?a:b)}))};
}
